[package]
name = "serv"
version = "0.1.0"
authors = ["yjh0502 <yjh0502@gmail.com>"]

[dependencies]
error-chain = "0.11"
futures = "0.1"
hyper = "0.11"
serde = "1"
serde_derive = "1"
serde_json = "1"
serde_qs = "0.3"
